Alter travis config to continue to support < Ruby 2.3
We were previously getting this version on older ruby versions:

$ gem update --system
Updating rubygems-update
Fetching: rubygems-update-3.0.4.gem (100%)
ERROR:  Error installing rubygems-update:
	rubygems-update requires Ruby version >= 2.3.0.
ERROR:  While executing gem ... (NoMethodError)
    undefined method `version' for nil:NilClass
The command "gem update --system" failed and exited with 1 during .

This change limits us to less than version 3 of RubyGems. This should be
changed once we have dropped support for Ruby 2.2